import { test, expect, type Browser, type Page } from '@playwright/test';

async function join(browser: Browser, code: string, name: string) {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(`/join/${code}`);
  await page.getByLabel('Your player name').fill(name + ' player');
  await page.getByRole('button', { name: 'Create a new character' }).click();
  await page.getByLabel('Character name', { exact: true }).fill(name);
  await page.getByLabel('Species or form').fill(name + ' custom species');
  await page.getByLabel('STR weapon name').fill(name + ' hammer');
  await page.getByRole('button', { name: 'Save character', exact: true }).click();
  await page.getByRole('button', { name: 'Join the party', exact: true }).click();
  await expect(page).toHaveURL(/\/campaign\//);
  await page.getByRole('button', { name: new RegExp(name + ' hammer') }).click();
  return { context, page };
}
test('a shared screen follows two players and advances only after both submit', async ({ page, browser }) => {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your campaigns' })).toBeVisible();
  await page.screenshot({ path: 'test-results/dashboard.png', fullPage: true });
  await page.getByRole('link', { name: 'Start an adventure' }).click();
  await page.getByLabel('Campaign name', { exact: true }).fill('The Lantern Road');
  await page.getByLabel('Setting', { exact: true }).fill('A glass city suspended above a violet ocean');
  await page.getByLabel('Practice table').check();
  await page.getByRole('button', { name: 'Create campaign', exact: true }).click();
  await expect(page).toHaveURL(/\/campaign\//);
  const id = new URL(page.url()).pathname.split('/')[2];
  const snapshot = await page.evaluate(async (id) => (await fetch(`/api/campaigns/${id}`)).json(), id);
  const first = await join(browser, snapshot.inviteCode, 'Mira');
  const second = await join(browser, snapshot.inviteCode, 'Rowan');
  const displayContext = await browser.newContext();
  const display = await displayContext.newPage();
  await display.goto(`/screen/${id}#${snapshot.displayToken}`);
  await expect(display.getByRole('heading', { name: 'The Lantern Road', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Begin the story' })).toBeEnabled();
  await page.getByRole('button', { name: 'Begin the story' }).click();
  await expect(first.page.getByLabel('Your action')).toBeEnabled();
  await first.page.getByLabel('Your action').fill('Mira examines the brass key.');
  await first.page.getByRole('button', { name: 'Submit action' }).click();
  await expect(display.getByText('Mira examines the brass key.', { exact: true })).toBeVisible();
  await expect(display.getByText('1 / 2 ready', { exact: true })).toBeVisible();
  await expect(second.page.getByLabel('Your action')).toBeEnabled();
  await second.page.getByLabel('Your action').fill('Rowan watches the doorway.');
  await second.page.getByRole('button', { name: 'Submit action' }).click();
  await expect(display.getByText('CHAPTER IN MOTION · TURN 1')).toBeVisible();
  await expect(display.getByText('Turn 2', { exact: true })).toBeVisible();
  await expect(display.locator('.roll-receipt')).toHaveCount(2);
  await expect(display.getByRole('button', { name: 'Submit action' })).toHaveCount(0);
  await display.screenshot({ path: 'test-results/shared-screen.png', fullPage: true });
  await first.page.setViewportSize({ width: 390, height: 844 });
  await first.page.screenshot({ path: 'test-results/player-mobile.png', fullPage: true });
  expect(await first.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await expect(page.getByText('Turn 2', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  await first.context.close();
  await second.context.close();
  await displayContext.close();
});
